### ISSUE TITLE
Erro run.py

### ISSUE THREAD

**Issue by Luc666-dreams** [Naegin/Flux#1]
Olá, estava lendo seu código e fazendo umas modificação, mais ainda estou me deparando com erros para executar o run.py
Os erros são "bobos" mais não estou sabendo resolver

Erros:  Traceback (most recent call last):
  File "C:\Users\n03xg\Desktop\Monitor Nike\Base monitor\run.py", line 1, in <module>
    from base import Flux
  File "C:\Users\n03xg\Desktop\Monitor Nike\Base monitor\base__init__.py", line 1, in <module>
    from .base import Flux
  File "C:\Users\n03xg\Desktop\Monitor Nike\Base monitor\base\base.py", line 3, in <module>
    from i18n import Files, Translator

Poderia me ajudar ?

**Comment by Naegin** [comment]
Mostra que o directorio não existe. :v:

**Comment by Naegin** [comment]
Qualquer coisa só adicionar meu discord Naegin#0002 pra qualquer dúvida.
